locadora/locadora/accounts/urls.py
from django.conf.urls import url
from .import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$',views.signup_view,name="signup"),
    url(r'^login/$',views.login_view,name="login"),
    url(r'^okay/$',views.okay),
    url(r'^okay1/$',views.okay1),
    url(r'^next/$',views.next),
    url(r'^log/$',views.log),
]

locadora/locadora/locadora/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import login_view, signup_view
from core.views import index, funcionarios, cargos, clientes, locacoes, veiculos, ajuda
from core.views import remover_cliente, remover_cargo, remover_funcionario, remover_veiculo, remover_locacao
from core.views import atualiza_cliente, atualiza_funcionario, atualiza_cargo
from core.views import  atualiza_veiculo, atualiza_locacao
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('funcionarios/', funcionarios, name='url_funcionario'),
    path('cargos/', cargos, name='url_cargo'),
    path('clientes/', clientes, name='url_cliente'),
    path('locacoes/', locacoes, name='url_locacao'),
    path('veiculos/', veiculos, name='url_veiculo'),
	path('ajuda/', ajuda, name='url_ajuda'),
    path('index/', index, name='url_index'),
    path('accounts/', include('accounts.urls')),

    path('atualizacliente/<int:pk>/', atualiza_cliente, name='url_atualizacliente'),
    path('atualizafuncionario/<int:pk>/', atualiza_funcionario, name='url_atualizafuncionario'),
    path('atualizacargo/<int:pk>/', atualiza_cargo, name='url_atualizacargo'),
    path('atualizaveiculo/<int:pk>/', atualiza_veiculo, name='url_atualizaveiculo'),
    path('atualizalocacao/<int:pk>/', atualiza_locacao, name='url_atualizalocacao'),

    path('remover_cliente/<int:pk>/', remover_cliente, name='url_removercliente'),
    path('remover_cargo/<int:pk>/', remover_cargo, name='url_removercargo'),
    path('remover_funcionario/<int:pk>/', remover_funcionario, name='url_removerfuncionario'),
    path('remover_veiculo/<int:pk>/', remover_veiculo, name='url_removerveiculo'),
    path('remover_locacao/<int:pk>/', remover_locacao, name='url_removerlocacao'),


]

locadora/locadora/core/models.py
from django.db import models

# Create your models here.


class Cliente(models.Model):
    ATIVO = 'ATIVO'
    INATIVO = 'INATIVO'
    STATUS = (
        (ATIVO, 'Ativo'),
        (INATIVO, 'Inativo'),
    )

    nome = models.CharField(max_length=200)
    cpf = models.CharField(max_length=15)
    #status = models.CharField(max_length=3)
    status = models.CharField(max_length=10, choices=STATUS)
    pontos_fidelidade = models.DecimalField(max_digits=7, decimal_places=2)

    def __str__(self):
        return self.nome


class Cargo(models.Model):

    nome = models.CharField(max_length=200)
    descricao = models.CharField(max_length=200)
    salario = models.DecimalField(max_digits=7, decimal_places=2)

    def __str__(self):
        return self.nome


class Funcionario(models.Model):

    nome = models.CharField(max_length=200)
    cpf = models.CharField(max_length=15)
    data_admissao = models.DateField()
    cargo = models.ForeignKey(Cargo, on_delete=models.CASCADE)

    def __str__(self):
        return self.nome


class Veiculo(models.Model):
    CUPE = 'CUPE'
    CROSSOVER = 'CROSSOVER'
    ESPORTIVO = 'ESPORTIVO'
    HATCH = 'HATCH'
    JIPE = 'JIPE'
    PICAPE = 'PICAPE'
    SEDAN = 'SEDAN'
    SUV = 'SUV'
    VAN = 'VAN E MINIVAM'

    TIPO = (
        (CUPE, 'Cupe'),
        (CROSSOVER, 'Crossover'),
        (ESPORTIVO, 'Esportivo'),
        (HATCH, 'Hacth'),
        (JIPE, 'Jipe'),
        (PICAPE, 'Picape'),
        (SEDAN, 'Sedan'),
        (SUV, 'SUV'),
        (VAN, 'Van/Minivam'),
    )

    DISPONIVEL = 'DISPONÍVEL'
    INDISPONIVEL = 'INDISPONÍVEL'
    STATUS_VEICULO = (
        (DISPONIVEL, 'Disponível'),
        (INDISPONIVEL,'Indisponível'),
    )

    modelo = models.CharField(max_length=200)
    cor = models.CharField(max_length=15)
    ano = models.IntegerField()
    placa = models.CharField(max_length=15)
    tipo = models.CharField(max_length=15, choices=TIPO)
    status = models.CharField(max_length=20, default='DISPONÍVEL')

    def __str__(self):
        return self.modelo


# <th>Código</th>
# <th>Data de Locação</th>
# <th>Data de Devolução</th>
# <th>Status</th>
# <th>Funcionário</th>
# <th>Cliente</th>
# <th>Veículo</th>

class Locacao(models.Model):
    EM_ABERTO = 'EM_ABERTO'
    FECHADA = 'FECHADA'
    DEVOLUCAO_STATUS = (
        (EM_ABERTO, 'Em Aberto'),
        (FECHADA, 'Fechada'),
    )

    data_locacao = models.DateField()
    data_devolucao = models.DateField()
    status = models.CharField(max_length=10, choices = DEVOLUCAO_STATUS)
    funcionario = models.ForeignKey(Funcionario, on_delete=models.CASCADE)
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    veiculo = models.ForeignKey(Veiculo, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'Locações'

    def __str__(self):
        return self.status

locadora/locadora/core/forms.py
from django import forms
from .models import Cliente, Cargo, Funcionario, Veiculo, Locacao
from django.core.exceptions import ValidationError
from django.contrib import messages
from pycpfcnpj import cpfcnpj

class ClienteForm(forms.ModelForm):

    nome = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    cpf = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    status = forms.ChoiceField(choices = Cliente.STATUS, widget=forms.Select(attrs={'class': 'form-control'}))
    pontos_fidelidade = forms.CharField(widget=forms.NumberInput(attrs={'class': 'form-control'}))

    class Meta:
        model = Cliente
        fields = ('nome','cpf','status','pontos_fidelidade')

    def clean(self):
        cleaned_data = super(ClienteForm, self).clean()
        cpf = cpfcnpj.validate(self.cleaned_data.get('cpf'))
        # verifico se o cpf não é válido
        if not cpf:
            self.add_error('cpf', 'CPF inválido')


class CargoForm(forms.ModelForm):

    nome = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    descricao = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    salario = forms.CharField(widget=forms.NumberInput(attrs={'class': 'form-control'}))

    class Meta:
        model = Cargo
        fields = ('nome','descricao','salario')


class FuncionarioForm(forms.ModelForm):

    nome = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    cpf = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    data_admissao = forms.DateField(widget=forms.DateTimeInput(attrs={'type':'date','class': 'form-control'}))
    #cargo = forms.ChoiceField(widget=forms.Select(attrs={'class': 'form-control'}))
    cargo = forms.ModelChoiceField(queryset=Cargo.objects.all(),widget=forms.Select(attrs={'class': 'form-control'}))

    class Meta:
        model = Funcionario
        fields = ('nome','cpf','data_admissao','cargo')

    def clean(self):
        cleaned_data = super(FuncionarioForm, self).clean()
        cpf = cpfcnpj.validate(self.cleaned_data.get('cpf'))
        # verifico se o cpf não é válido
        if not cpf:
            self.add_error('cpf', 'CPF inválido')


class VeiculoForm(forms.ModelForm):

    modelo = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    cor = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    ano = forms.CharField(widget=forms.NumberInput(attrs={'class': 'form-control'}))
    placa = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    tipo = forms.ChoiceField(choices=Veiculo.TIPO,
                             widget=forms.Select(attrs={'class': 'form-control'}))
    
    class Meta:
        model = Veiculo
        fields = ['modelo','cor','ano','placa','tipo']


class LocacaoForm(forms.ModelForm):

    data_locacao = forms.DateField(widget=forms.DateTimeInput(attrs={'type':'date','class': 'form-control'}))
    data_devolucao = forms.DateField(widget=forms.DateTimeInput(attrs={'type': 'date', 'class': 'form-control'}))

    #status = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    status = forms.ChoiceField(choices= Locacao.DEVOLUCAO_STATUS,
                               widget=forms.Select(attrs={'class': 'form-control'}))

    funcionario = forms.ModelChoiceField(queryset=Funcionario.objects.all(),
                                         widget=forms.Select(attrs={'class': 'form-control'}))

    cliente = forms.ModelChoiceField(queryset=Cliente.objects.filter(status='ATIVO'),
                                         widget=forms.Select(attrs={'class': 'form-control'}))

    veiculo = forms.ModelChoiceField(queryset=Veiculo.objects.filter(status='DISPONÍVEL'),
                                         widget=forms.Select(attrs={'class': 'form-control'}))

    class Meta:
        model = Locacao
        fields = ('data_locacao','data_devolucao','status','funcionario','cliente', 'veiculo')

locadora/locadora/core/views.py
from django.shortcuts import render, redirect
from accounts.views import login_view, signup_view
from .forms import ClienteForm, CargoForm, FuncionarioForm
from .forms import VeiculoForm, LocacaoForm
from .models import Cliente, Cargo, Funcionario, Veiculo, Locacao

from django.contrib import messages
from datetime import date

def index(request):
    return render(request, 'core/index.html')

def ajuda(request):
    return render(request, 'core/ajuda.html')

def funcionarios(request):
    data = {}
    data['funcionarios'] = Funcionario.objects.all()  # Carregando clientes do banco

    if request.method == 'POST':
        form = FuncionarioForm(request.POST)
        if form.is_valid():
            form.save()  # Salva
            return redirect('url_funcionario')
        data['form'] = form
    else:
        data['form'] = FuncionarioForm()
    return render(request, 'core/funcionarios.html', data)

def cargos(request):
    data = {}
    data['cargos'] = Cargo.objects.all()  # Carregando clientes do banco

    if request.method == 'POST':
        form = CargoForm(request.POST)
        if form.is_valid():
            form.save()  # Salva
            return redirect('url_cargo')
    else:
        data['form'] = CargoForm()
    return render(request, 'core/cargos.html', data)

def veiculos(request):
    data = {}
    dataToday = date.today()
    vei = Veiculo.objects.all()
    for v in vei:
        print(v)
        l = Locacao.objects.filter(veiculo=v.pk).filter( data_devolucao__gte = dataToday)
        if l.count() > 0:
            v.status = 'INDISPONÍVEL'

    data['veiculos'] = vei


    #data['veiculos'] = Veiculo.objects.all()  # Carregando clientes do banco

    if request.method == 'POST':
        form = VeiculoForm(request.POST)
        if form.is_valid():
            form.save()  # Salva
            return redirect('url_veiculo')
    else:
        data['form'] = VeiculoForm()
    return render(request, 'core/veiculos.html', data)

def clientes(request):
    data = {}
    data['clientes'] = Cliente.objects.all()  # Carregando clientes do banco

    if request.method == 'POST':
        form = ClienteForm(request.POST)
        if form.is_valid():
            form.save()  # Salva
            return redirect('url_cliente')
        data['form'] = form
    else:
        data['form'] = ClienteForm()
        #form = ClienteForm()
    return render(request, 'core/clientes.html', data)

def locacoes(request):
    data = {}
    data['locacoes'] = Locacao.objects.all()  # Carregando clientes do banco

    if request.method == 'POST':
        form = LocacaoForm(request.POST)
        r = Locacao.objects.filter(veiculo=request.POST.get('veiculo')).filter(data_locacao__gte = request.POST.get('data_locacao')).filter( data_devolucao__lte = request.POST.get('data_devolucao'))

        r2 = Locacao.objects.filter(veiculo=request.POST.get('veiculo')).filter( data_devolucao__gte = request.POST.get('data_locacao'))

        if (r.count() + r2.count()) == 0:
            if form.is_valid() :
                form.save()  # Salva
        else:
            print('Periodo de locacao invalido')
            messages.add_message(request, messages.WARNING, "Periodo de locação inválido!")

        data['form'] = form
    else:
        data['form'] = LocacaoForm()
        # form = ClienteForm()
    return render(request, 'core/locacoes.html', data)


# ATUALIZA

def atualiza_cliente(request, pk):
    data = {}
    cliente = Cliente.objects.get(pk=pk)
    form = ClienteForm(request.POST or None, instance=cliente) #Passar o formulario preenchido

    # Verificar se o form é valido
    if form.is_valid():
        form.save()  # Salva
        return redirect('url_cliente')  # E redireciona para a listagem

    data['form'] = form
    data['clientes'] = cliente # Enviando a transação pela URL, para ser possivel remover

    return render(request, 'core/atualizacliente.html', data)


def atualiza_funcionario(request, pk):
    data = {}
    funcionario = Funcionario.objects.get(pk=pk)
    form = FuncionarioForm(request.POST or None, instance=funcionario) #Passar o formulario preenchido

    # Verificar se o form é valido
    if form.is_valid():
        form.save()  # Salva
        return redirect('url_funcionario')  # E redireciona para a listagem

    data['form'] = form

    return render(request, 'core/atualizafuncionario.html', data)


def atualiza_cargo(request, pk):
    data = {}
    cargo = Cargo.objects.get(pk=pk)
    form = CargoForm(request.POST or None, instance=cargo)

    if form.is_valid():
        form.save()
        return redirect('url_cargo')

    data['form'] = form

    return render(request, 'core/atualizacargo.html', data)


def atualiza_veiculo(request, pk):
    data = {}
    veiculo = Veiculo.objects.get(pk=pk)
    form = VeiculoForm(request.POST or None, instance=veiculo)

    # Verificar se o form é valido
    if form.is_valid():
        form.save()  # Salva
        return redirect('url_veiculo')  # E redireciona para a listagem

    data['form'] = form

    return render(request, 'core/atualizaveiculo.html', data)


def atualiza_locacao(request, pk):
    data = {}
    locacao = Locacao.objects.get(pk=pk)
    form = LocacaoForm(request.POST or None, instance=locacao)

    if form.is_valid():
        form.save()
        return redirect('url_locacao')

    data['form'] = form

    return render(request, 'core/atualizalocacao.html', data)

# REMOVER

def remover_cliente(request, pk):
    cliente = Cliente.objects.get(pk=pk)
    cliente.delete()
    return redirect('url_cliente')

def remover_cargo(request, pk):
    cargo = Cargo.objects.get(pk=pk)
    cargo.delete()
    return redirect('url_cargo')

def remover_funcionario(request, pk):
    funcionario = Funcionario.objects.get(pk=pk)
    funcionario.delete()
    return redirect('url_funcionario')

def remover_veiculo(request, pk):
    veiculo = Veiculo.objects.get(pk=pk)
    veiculo.delete()
    return redirect('url_veiculo')

def remover_locacao(request, pk):
    locacao = Locacao.objects.get(pk=pk)
    locacao.delete()
    return redirect('url_locacao')

locadora/locadora/core/templates/core/ajuda.html
{% load static %}
<!DOCTYPE html>
<html>
<link rel="stylesheet" href="{% static 'css/ajuda.css' %}" >
<body>
<h1> Como usar a aplicação?</h1>
<div>
<p> Após Cadastrar um usuario para acessar a aplicação tem se acesso ao página inicial, nesta página tem-se acesso a barra de opções que o leva para a opção desejada de cadastrado
de acordo com o respectivo nome. Esta aplicação tem como objetivo a gerencia básica para uma locadora de veiculos que precisa
registrar os seus dados sobrel locações de veiculos funcionarios etc.
Possui as seguintes funcionalidades para cadastro,
<br>
1. Menu de Login para que apenas usuarios cadastrados tenham acesso
<br>
2. Opções para cadastros diversas
<br>
2.1 Cadastro de Veiculos Disponiveis para Alugar
<br>
2.2 Cadastro de Locações Realizadas
<br>
2.3 Cadastro de Empregados da locadora
<br>
2.4 Cadastro de Respectivas funções para Empregados para fins de pagamento.
<br>
2.5 Cadastro de Clientes
<br>
3. Página de ajuda
<a href="{% url 'url_index' %}">Voltar</a>
</p>
</div>
</body>
</html>

locadora/locadora/core/templates/core/atualizacargo.html
{% extends "core/base.html" %}

{% load static %}

{% block content %}
<div class="container">
	
	<form method="post">
		{% csrf_token %}
		<fieldset>
	  		<legend>Atualiza Cargo</legend>
			{{ form.as_p }}

	  		<button type="submit" class="btn btn-primary">
	  				<span class="glyphicon glyphicon-thumbs-up"></span>
	  				Atualizar
			</button>
		</fieldset>  
	</form> 			
</div> <!-- fim .container 1 --> 

<div class="container">
 	<br /> <br /> 
</div> <!-- fim .container 2 -->
	

</div><!-- fim .panel-body -->
</div><!-- fim .panel -->

{% endblock %}

locadora/locadora/core/templates/core/atualizacliente.html
{% extends "core/base.html" %}

{% load static %}

{% block content %}

<div class="container">
		<form method="post">
		<fieldset>
	  		<legend>Atualizar Cliente</legend>
			{% csrf_token %}
			<div class="form-group">
				{{ form.as_p}}
	  		</div>

	  		<button type="submit" class="btn btn-primary">
	  				<span class="glyphicon glyphicon-thumbs-up"></span>
	  				Atualizar
			</button>
		</fieldset>
	</form>
</div> <!-- fim .container 1 -->

<div class="container">
 	<br /> <br />
</div> <!-- fim .container 2 -->

</div><!-- fim .panel-body -->
</div><!-- fim .panel -->

{% endblock %}

locadora/locadora/core/templates/core/atualizafuncionario.html
{% extends "core/base.html" %}

{% load static %}

{% block content %}
<div class="container">
	
	<form method="post">
		{% csrf_token %}
		<fieldset>
	  		<legend>Atualiza Funcionario</legend>
			{{ form.as_p }}
	  
	  		<button type="submit" class="btn btn-primary">
	  				<span class="glyphicon glyphicon-thumbs-up"></span>
	  				Atualizar
			</button>
		</fieldset>  
	</form> 			
</div> <!-- fim .container 1 --> 

<div class="container">
 	<br /> <br /> 
</div> <!-- fim .container 2 -->

</div><!-- fim .panel-body -->
</div><!-- fim .panel -->

{% endblock %}

locadora/locadora/core/templates/core/atualizalocacao.html
{% extends "core/base.html" %}

{% load static %}

{% block content %}

<div class="container">

	<form method="post">
		{% csrf_token %}
		<fieldset>
	  		<legend>Atualiza Locação</legend>
			{{ form.as_p }}
			<button type="submit" class="btn btn-primary">
	  				<span class="glyphicon glyphicon-thumbs-up"></span>
	  				Atualizar
			</button>
		</fieldset>
	</form>
</div> <!-- fim .container 1 -->

<div class="container">
 	<br /> <br />
</div> <!-- fim .container 2 -->

</div><!-- fim .panel-body -->
</div><!-- fim .panel -->

{% endblock %}

locadora/locadora/core/templates/core/clientes.html
{% extends "core/base.html" %}

{% load static %}

{% block content %}


<div class="container">

	<form method="post">
		<fieldset>
	  		<legend>Novo Cliente</legend>
			{% csrf_token %}
			<div class="form-group">
				{{ form.as_p}}
	  		</div>

	  		<button type="submit" class="btn btn-primary">
	  				<span class="glyphicon glyphicon-thumbs-up"></span>
	  				Cadastrar
			</button>
		</fieldset>
	</form>
</div> <!-- fim .container 1 -->

<div class="container">
 	<br /> <br />
</div> <!-- fim .container 2 -->


<div class="container">
  <div class="panel panel-default">
  		<div class="panel-heading">
    		<h2 class="panel-title">Lista de Clientes</h2>
 	 	</div><!-- fim .panel-heading -->

		<div class="panel-body">
  			<table class="table table-hover">
  				<tr>
  						<th>Código</th>
  						<th>Nome</th>
  						<th>Cpf</th>
              			<th>Status</th>
  						<th>Pontos de Fidelidade</th>
  						<th>Opções</th>
  				</tr>
    				{% for cliente in clientes %}
    				<tr>
						<td class="col-md-1">{{ cliente.id}}</td>
						<td class="col-md-2">{{ cliente.nome }}</td>
    					<td class="col-md-2">{{ cliente.cpf }}</td>
						<td class="col-md-1">{{ cliente.status }}</td>
						<td class="col-md-1">{{ cliente.pontos_fidelidade }}</td>

    					<td class="col-md-2">
							<a class="btn btn-warning" href="{% url 'url_atualizacliente' cliente.id %}" role="button">Editar</a>
    						<a class="btn btn-danger" href="{% url 'url_removercliente' cliente.id %}" role="button">Excluir</a>
    					</td>
					</tr>
				{% endfor %}
    			</table>

 		</div><!-- fim .panel-body -->
	</div><!-- fim .panel -->
</div><!-- fim .container 3 -->


<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.mask.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.inputmask.bundle.js' %}"></script>

<script type="text/javascript">
  $(document).ready(function(){
    $('#id_cpf').mask('000.000.000-00');
  });

</script>

{% endblock %}

locadora/locadora/core/templates/core/funcionarios.html
{% extends "core/base.html" %}

{% load static %}

{% block content %}
<div class="container">
	
	<form action="" method="post">
		{% csrf_token %}
		<fieldset>
	  		<legend>Novo Funcionario</legend>
			{{ form.as_p }}
	  
	  		<button type="submit" class="btn btn-primary">
	  				<span class="glyphicon glyphicon-thumbs-up"></span>
	  				Cadastrar
			</button>
		</fieldset>  
	</form> 			
</div> <!-- fim .container 1 --> 

<div class="container">
 	<br /> <br /> 
</div> <!-- fim .container 2 -->
	
	
<div class="container">
  <div class="panel panel-default">
  		<div class="panel-heading">
    		<h2 class="panel-title">Lista de Funcionários</h2>
 	 	</div><!-- fim .panel-heading -->
		
		<div class="panel-body">  
  			<table class="table table-hover">
  				<tr>
  						<th>Código</th>
  						<th>Nome</th>
  						<th>CPF</th>
  						<th>Data Admissão</th>
  						<th>Cargo</th>
  						<th>Opções</th>
  				</tr>
				{% for funcionario in funcionarios %}
  				<tr>
    					<td class="col-md-1">{{ funcionario.id }}</td>
    					<td class="col-md-3">{{ funcionario.nome }}</td>
    					<td class="col-md-1">{{ funcionario.cpf}}</td>
    					<td class="col-md-2">{{ funcionario.data_admissao }}</td>
    					<td class="col-md-1">{{ funcionario.cargo }}</td>

    					<td class="col-md-2">
							<a class="btn btn-warning" href="{% url 'url_atualizafuncionario' funcionario.id%}" role="button">Editar</a>
    						<a class="btn btn-danger" href="{% url 'url_removerfuncionario' funcionario.id%}" role="button">Excluir</a>
    					</td>
    			</tr>
				{% endfor %}
    			
    			</table>
    			
 		</div><!-- fim .panel-body -->
	</div><!-- fim .panel -->
</div><!-- fim .container 3 -->


<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.mask.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.inputmask.bundle.js' %}"></script>

<script type="text/javascript">
  $(document).ready(function(){
    $('#id_cpf').mask('000.000.000-00');
  });

</script>

{% endblock %}

locadora/locadora/core/templates/core/veiculos.html
{% extends "core/base.html" %}

{% load static %}

{% block content %}


<div class="container">

  <form action="{% url 'url_veiculo' %}" method="post">
      {% csrf_token %}
    <fieldset>
        <legend>Novo Veículo</legend>
        {{ form.as_p }}

        <button type="submit" class="btn btn-primary">
            <span class="glyphicon glyphicon-thumbs-up"></span>
            Cadastrar
      </button>
    </fieldset>
  </form>
</div> <!-- fim .container 1 -->

<div class="container">
  <br /> <br />
</div> <!-- fim .container 2 -->


<div class="container">
  <div class="panel panel-default">
      <div class="panel-heading">
        <h2 class="panel-title">Lista de Veículos</h2>
    </div><!-- fim .panel-heading -->

    <div class="panel-body">
        <table class="table table-hover">
          <tr>
              <th>Código</th>
              <th>Modelo</th>
              <th>Cor</th>
              <th>Ano</th>
              <th>Placa</th>
              <th>Tipo</th>
              <th>Status</th>
              <th>Opções</th>
          </tr>
            {% for veiculo in veiculos %}
            <tr>
              <td class="col-md-1">{{ veiculo.id }}</td>
              <td class="col-md-1">{{ veiculo.modelo }}</td>
              <td class="col-md-2">{{ veiculo.cor }}</td>
              <td class="col-md-1">{{ veiculo.ano }}</td>
              <td class="col-md-1">{{ veiculo.placa }}</td>
              <td class="col-md-2">{{ veiculo.tipo }}</td>
              <td class="col-md-2">{{ veiculo.status }}</td>

              <td class="col-md-3">
                  <a class="btn btn-warning" href="{% url 'url_atualizaveiculo' veiculo.pk %}" role="button">Editar</a>
                  <a class="btn btn-danger" href="{% url 'url_removerveiculo' veiculo.pk %}" role="button">Excluir</a>
              </td>
            </tr>
            {% endfor %}
          </table>

    </div><!-- fim .panel-body -->
  </div><!-- fim .panel -->
</div><!-- fim .container 3 -->

<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.mask.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.inputmask.bundle.js' %}"></script>

<script type="text/javascript">
  $(document).ready(function(){
    $('#id_placa').mask('aaa-9999');
  });
</script>

{% endblock %}